#!/usr/bin/env python

import argparse
import os
import shutil

import botocore.session

bs = botocore.session.get_session()
batch_client = bs.create_client("batch")

parser = argparse.ArgumentParser()
parser.add_argument("job_definitions")
parser.add_argument("command", nargs=argparse.REMAINDER)

args = parser.parse_args()

jobs = [j.strip() for j in args.job_definitions.split(",") if j.strip()]

env_vars = {}

for job in jobs:
    resp = batch_client.describe_job_definitions(
        jobDefinitionName=job,
    )

    for definition in resp.get("jobDefinitions") or []:
        for entry in definition.get("containerProperties", {}).get("environment", {}):
            env_vars[entry["name"]] = entry["value"]

new_environ = os.environ.copy()
new_environ.update(env_vars)

exec_path = args.command[0]
if "/" not in exec_path:
    maybe_exec_path = shutil.which(exec_path)
    if maybe_exec_path:
        exec_path = maybe_exec_path

os.execve(exec_path, args.command, new_environ)
